# Generated by Django 5.2.10 on 2026-01-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="intro_test_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="intro_test_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
