# Generated by Django 5.2.10 on 2026-01-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_profile_intro_test_score_profile_intro_test_taken_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="content_markdown",
            field=models.TextField(
                blank=True, help_text="Session content and tasks (Markdown allowed)"
            ),
        ),
        migrations.AddField(
            model_name="session",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
