# Generated by Django 5.2.10 on 2026-01-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_sessiontemplate_alter_profile_next_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_mentor",
            field=models.BooleanField(default=False),
        ),
    ]
