# Generated by Django 5.2.10 on 2026-01-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_session_is_mentor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="is_mentor",
        ),
        migrations.AddField(
            model_name="profile",
            name="is_mentor",
            field=models.BooleanField(default=False),
        ),
    ]
