# Generated by Django 5.2.10 on 2026-01-16 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="subject",
        ),
    ]
