# Generated by Django 5.2.10 on 2026-01-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0008_remove_message_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="end_test_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="end_test_taken_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
