# Generated by Django 5.2.10 on 2026-01-16 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0009_profile_end_test_score_profile_end_test_taken_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="next_meeting_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_meeting_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_meeting_tool",
            field=models.CharField(
                blank=True,
                choices=[
                    ("zoom", "Zoom"),
                    ("meet", "Google Meet"),
                    ("teams", "Microsoft Teams"),
                    ("other", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="next_meeting_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name="Session",
        ),
    ]
