# Generated by Django 5.2.10 on 2026-01-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0010_profile_next_meeting_at_profile_next_meeting_notes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="sessiontemplate",
            name="mentor_content_markdown",
            field=models.TextField(
                blank=True,
                help_text="Mentor-only notes and guidance (Markdown allowed)",
            ),
        ),
    ]
